configuration: Release
test:
  assemblies:
    - Argu.Tests.dll

after_build:
  # dotnet cli version
  - ps: $env:CLI_VERSION = "1.0.0.001494"
  # return to repo root
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%"
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnet"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "beta" -version "$env:CLI_VERSION"'
  # set DOTNET_HOME env var and add dotnet bin to PATH
  - ps: $env:DOTNET_HOME = "$env:DOTNET_INSTALL_DIR\cli\bin"
  - ps: $env:Path = "$env:DOTNET_HOME;$env:Path"
  # check dotnet
  - ps: echo "Dotnet:"
  - ps: (Get-Command dotnet).Path
  - ps: dotnet --version
  # build it
  - cmd: dotnet restore
  - cmd: cd ".\src\Argu"
  - cmd: dotnet build
